### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by vladie0** [PRIDE-Cluster/cluster-data-generation#2]
Dear PRIDE-Cluster, 

I encouter the following issues attempting to install cluster-data-generation.
The following error occurs when running mvn clean (similar errors runs when running mvn install)

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /home/vladie/cluster_data_generation/searchgui/pom.xml of /home/vladie/cluster_data_generation/pom.xml does not exist @ 
[ERROR] Child module /home/vladie/cluster_data_generation/denovogui/pom.xml of /home/vladie/cluster_data_generation/pom.xml does not exist @ 
[ERROR] Child module /home/vladie/cluster_data_generation/peptide-shaker/pom.xml of /home/vladie/cluster_data_generation/pom.xml does not exist @ 
[ERROR] Child module /home/vladie/cluster_data_generation/pride-asa-pipeline/pom.xml of /home/vladie/cluster_data_generation/pom.xml does not exist @ 
[ERROR] Child module /home/vladie/cluster_data_generation/pride-parameters/pom.xml of /home/vladie/cluster_data_generation/pom.xml does not exist @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project uk.ac.ebi.pride.cluster:cluster-data-generation:0.0.1-SNAPSHOT (/home/vladie/cluster_data_generation/pom.xml) has 5 errors
[ERROR]     Child module /home/vladie/cluster_data_generation/searchgui/pom.xml of /home/vladie/cluster_data_generation/pom.xml does not exist
[ERROR]     Child module /home/vladie/cluster_data_generation/denovogui/pom.xml of /home/vladie/cluster_data_generation/pom.xml does not exist
[ERROR]     Child module /home/vladie/cluster_data_generation/peptide-shaker/pom.xml of /home/vladie/cluster_data_generation/pom.xml does not exist
[ERROR]     Child module /home/vladie/cluster_data_generation/pride-asa-pipeline/pom.xml of /home/vladie/cluster_data_generation/pom.xml does not exist
[ERROR]     Child module /home/vladie/cluster_data_generation/pride-parameters/pom.xml of /home/vladie/cluster_data_generation/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by ypriverol** [comment]
Hi @vladie0 are you planning to run the following pipeline on your side? How are you planning to estimate the use it?

**Comment by vladie0** [comment]
Hi Ypriverol, 
I'm particularly interested in extracting project/assay parameters from PRIDE projects/assays.
Ideally, I'm interested in extracting in creating a searchGUI compatible parameter file for a project/assay of interest. 

Is this currently possible? How accurate and error-proof is the parameter extraction step.
We've used PRIDE-ASAP and modified version of PRIDE-ASAP, the resulting parameter extraction provided many errors, ranging from unable to process the project in question to wrong prediction of modifications/enzymes

**Comment by ypriverol** [comment]
cool Thanks @vladie0 , I'm running in my side the parameter generation. As I said in my email is better if we run here the parameter extraction. I have generated this for 12000 assays now. I would be great if you can let me know the assays you are interested, I can provide them to you, you check how they look and we can try to fix together the code. Then @Javasaurus and I can update the code and re-run the project. 

About your error, this is because you need to update recursively all the submodules of the project. Then you should be able to run the tool. `git submodule update --recursive`

**Comment by vladie0** [comment]
Hi Ypriverol, 

We periodically reprocesses public repositories from PRIDE, meaning that we reprocess them one by to find new evidence for peptides in our database.

I have several question concerning the parameter extraction:
Are you able to extract parameters from all PRIDE project, incomplete projects as well as project without PRIDE xml files (only identification files in the form of MzIdentMl, pepXML or mzTab). Secondly, are you able to extract parameters from files where only ThermoRAW files are present (not mgf) and process them.
Are you generating parameter files for all species, if not, which species are you currently processing
Have you examined the correctness of the extracted parameters ? or how accurate the current prediction pipeline is in predicting the parameters for a project ?

**Comment by ypriverol** [comment]
@vladie0 

Some questions here: 

1- We only do it for Complete Submissions (mzId , PRIDE XML). 
2- We dont take into account the RAW data only the peak lists. 
3- I personally have check a couple of predictions and they work fine. But Would be great if you give me a set of assays that didn't work for you before to see how they looks in the current implementation.

**Comment by vladie0** [comment]
What input files does the software require before It can run (PRIDE XML/MzIdentMl file + mgf file)? 

Do you have plans to extend support to uncompleted projects, extracting the correct parameters from pepXML/MzIdentML/mzTab files ? 

What information do you extract from peak list files that you can't from MzIdentMl files ?

**Comment by ypriverol** [comment]
@vladie0 do you have an skype user we can intereact more quick and @Javasaurus is interested to interact

**Comment by ypriverol** [comment]
@vladie0 can you let me know previous projects that you have used and I can send you the parameters for them, to detect if they are fine and well predicted.

**Comment by vladie0** [comment]
Hi Yasset,

I suggest to discuss several aspects over Skype, including the testing of several projects and compare the performance of the upgraded software.
My supervisor is unable to join, I suggest that we continue our discussion.

Would it perhaps be possible to suggest several moments convenient for you to have a Skype meeting (I'm located in the gmt+1 timezone)

Kind Regards,
Volodimir Olexiouk

Sent from VMware Boxer

On 7 Dec 2017 8:29 am, Yasset Perez-Riverol <notifications@github.com> wrote:

@vladie0<https://github.com/vladie0> can you let me know previous projects that you have used and I can send you the parameters for them, to detect if they are fine and well predicted.

**Comment by ypriverol** [comment]
this is my email, can you send me your skype call to yperez@ebi.ac.uk
